# Generated by Django 4.2.27 on 2025-12-23 05:31

from django.db import migrations, models
import persons.validators


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, validators=[persons.validators.validate_cpf_numbers]),
        ),
    ]
